# Generated by Django 3.2.9 on 2021-12-26 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='None', max_length=30)),
                ('description', models.TextField(default='None')),
                ('birthDate', models.DateField()),
                ('slug', models.SlugField(default='None')),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=10)),
                ('image', models.ImageField(default='default_author_1.jpg', upload_to='author_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
