# Generated by Django 3.2.9 on 2021-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='test-slug'),
            preserve_default=False,
        ),
    ]
