# Generated by Django 3.2.9 on 2021-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20211120_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.FloatField(default=None),
        ),
    ]
