# Generated by Django 3.2.9 on 2021-12-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_author_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
    ]
