# Generated by Django 3.2.9 on 2021-12-21 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_remove_author_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='book_images/BookDefault.png', upload_to='book_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=10),
        ),
    ]
