# Generated by Django 3.2.9 on 2021-12-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_author_image'),
        ('authors', '0010_auto_20211221_2304'),
    ]

    operations = [
    ]
