# Generated by Django 3.2.9 on 2021-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211120_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
