# Generated by Django 3.2.9 on 2021-11-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='Slug',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='Title',
        ),
        migrations.AddField(
            model_name='genre',
            name='Genre',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
