# Generated by Django 3.2.9 on 2021-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211120_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='Genre',
            new_name='genreName',
        ),
    ]
