# Generated by Django 3.2.9 on 2021-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_genre_genre_genrename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='None', max_length=10),
        ),
    ]
