# Generated by Django 3.2.9 on 2021-11-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20211120_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRequest',
        ),
    ]
