# Generated by Django 3.2.9 on 2021-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20211130_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
