# Generated by Django 3.2.9 on 2021-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20211201_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='UserDefault.png', upload_to='book_images'),
        ),
    ]
