# Generated by Django 3.2.9 on 2021-12-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20211130_1713'),
        ('books', '0015_alter_book_image'),
    ]

    operations = [
    ]
