# Generated by Django 3.2.9 on 2021-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_merge_0011_auto_20211130_1713_0015_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
