# Generated by Django 3.2.9 on 2021-12-22 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20211216_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book_1.jpg', upload_to='book_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
