# Generated by Django 3.2.9 on 2021-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211120_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/UserDefault.png', upload_to='profile_images'),
        ),
    ]
