# Generated by Django 3.2.9 on 2021-12-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211225_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='None', max_length=50, verbose_name='Telefon'),
        ),
    ]
